definitions:
  dto.ChangeChatRequest:
    properties:
      new_description:
        maxLength: 254
        minLength: 1
        type: string
      new_title:
        maxLength: 38
        minLength: 1
        type: string
    type: object
  dto.ChangePasswordRequest:
    properties:
      confirm_new_password:
        type: string
      new_password:
        type: string
      old_password:
        type: string
    required:
    - confirm_new_password
    - new_password
    - old_password
    type: object
  dto.ChangeUserProfileRequest:
    properties:
      new_description:
        maxLength: 254
        type: string
      new_image:
        $ref: '#/definitions/multipart.FileHeader'
      new_username:
        type: string
    type: object
  dto.ChangeUserProfileResponse:
    properties:
      changed_fields:
        $ref: '#/definitions/dto.ChangeUserProfileRequest'
      message:
        type: string
    type: object
  dto.ChatDTO:
    properties:
      description:
        type: string
      id:
        type: integer
      owner_id:
        type: integer
      title:
        type: string
    type: object
  dto.ChatsForUserResponse:
    properties:
      chats:
        items:
          $ref: '#/definitions/dto.ChatDTO'
        type: array
    type: object
  dto.ConfirmResetPasswordRequest:
    properties:
      code:
        type: integer
      confirm_new_password:
        type: string
      new_password:
        type: string
    required:
    - code
    - confirm_new_password
    - new_password
    type: object
  dto.CreateChatRequest:
    properties:
      description:
        maxLength: 254
        minLength: 1
        type: string
      title:
        maxLength: 38
        minLength: 1
        type: string
    required:
    - description
    - title
    type: object
  dto.ErrorResponse:
    properties:
      error:
        type: string
    required:
    - error
    type: object
  dto.LoginRequest:
    properties:
      password:
        type: string
      username_or_email:
        type: string
    required:
    - password
    - username_or_email
    type: object
  dto.MessageResponse:
    properties:
      message:
        type: string
    type: object
  dto.RegisterRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - confirm_password
    - email
    - password
    - username
    type: object
  dto.RegisterResponse:
    properties:
      message:
        type: string
      status:
        type: boolean
    required:
    - message
    - status
    type: object
  dto.ResetPasswordRequest:
    properties:
      username_or_email:
        type: string
    required:
    - username_or_email
    type: object
  dto.ResetPasswordResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  dto.UserProfile:
    properties:
      created_at:
        type: string
      description:
        type: string
      image:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  multipart.FileHeader:
    properties:
      filename:
        type: string
      header:
        $ref: '#/definitions/textproto.MIMEHeader'
      size:
        type: integer
    type: object
  textproto.MIMEHeader:
    additionalProperties:
      items:
        type: string
      type: array
    type: object
info:
  contact: {}
paths:
  /accounts/auth/confirm-account:
    get:
      consumes:
      - application/json
      description: Confirm users email
      parameters:
      - description: Token to confirm account
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: User confirm registration
      tags:
      - Auth
  /accounts/auth/login:
    post:
      consumes:
      - application/json
      description: Login to account
      parameters:
      - description: Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Login
      tags:
      - Auth
  /accounts/auth/logout:
    delete:
      consumes:
      - application/json
      description: Logout the session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Logout
      tags:
      - Auth
  /accounts/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user behind the selected fields
      parameters:
      - description: Data to register
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: User register
      tags:
      - Auth
  /accounts/profile/{username}:
    get:
      consumes:
      - application/json
      description: View user profile
      parameters:
      - description: Username of the user
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserProfile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Profile
      tags:
      - profile
  /accounts/profile/change-password:
    put:
      consumes:
      - application/json
      description: Change password
      parameters:
      - description: Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Change password
      tags:
      - profile
  /accounts/profile/edit:
    patch:
      consumes:
      - multipart/form-data
      description: Edit user profile
      parameters:
      - description: Update username
        in: formData
        name: new_username
        type: string
      - description: Update description
        in: formData
        name: new_description
        type: string
      - description: Update image
        in: formData
        name: new_image
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ChangeUserProfileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Edit profile
      tags:
      - profile
  /accounts/profile/reset-password:
    put:
      consumes:
      - application/json
      description: Reset user password
      parameters:
      - description: Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResetPasswordResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Reset password
      tags:
      - profile
  /accounts/profile/reset-password/confirm/{token}:
    put:
      consumes:
      - application/json
      description: Confirm reset user password
      parameters:
      - description: Token
        in: path
        name: token
        required: true
        type: string
      - description: Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.ConfirmResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: confirm reset password
      tags:
      - profile
  /messenger/chat/all:
    get:
      consumes:
      - application/json
      description: get all the chats in which the user consists
      parameters:
      - description: Search name
        in: query
        name: search
        type: string
      - description: Page
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ChatsForUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get chats for user
      tags:
      - Chat
  /messenger/chat/create:
    post:
      consumes:
      - application/json
      description: Creating a new chat
      parameters:
      - description: Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.CreateChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create chat
      tags:
      - Chat
  /messenger/chat/delete/{chatId}:
    delete:
      consumes:
      - application/json
      description: deleting a chat
      parameters:
      - description: Chat ID
        in: path
        name: chatId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Delete chat
      tags:
      - Chat
  /messenger/chat/edit/{chatId}:
    patch:
      consumes:
      - application/json
      description: change chat
      parameters:
      - description: Chat ID
        in: path
        name: chatId
        required: true
        type: integer
      - description: Data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.ChangeChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Change chat
      tags:
      - Chat
  /messenger/chat/invite:
    post:
      consumes:
      - application/json
      description: inviting a user to an existing chat
      parameters:
      - description: Invitee username
        in: query
        name: invitee
        required: true
        type: string
      - description: chat id to invite to
        in: query
        name: chat_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Invite to chat
      tags:
      - Chat
swagger: "2.0"
