// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "libs/src/internal/dto"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IBaseRedisRepository is an autogenerated mock type for the IBaseRedisRepository type
type IBaseRedisRepository struct {
	mock.Mock
}

type IBaseRedisRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IBaseRedisRepository) EXPECT() *IBaseRedisRepository_Expecter {
	return &IBaseRedisRepository_Expecter{mock: &_m.Mock}
}

// CountAll provides a mock function with given fields: Ctx
func (_m *IBaseRedisRepository) CountAll(Ctx context.Context) (int64, error) {
	ret := _m.Called(Ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountAll")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(Ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(Ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(Ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBaseRedisRepository_CountAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAll'
type IBaseRedisRepository_CountAll_Call struct {
	*mock.Call
}

// CountAll is a helper method to define mock.On call
//   - Ctx context.Context
func (_e *IBaseRedisRepository_Expecter) CountAll(Ctx interface{}) *IBaseRedisRepository_CountAll_Call {
	return &IBaseRedisRepository_CountAll_Call{Call: _e.mock.On("CountAll", Ctx)}
}

func (_c *IBaseRedisRepository_CountAll_Call) Run(run func(Ctx context.Context)) *IBaseRedisRepository_CountAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IBaseRedisRepository_CountAll_Call) Return(_a0 int64, _a1 error) *IBaseRedisRepository_CountAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IBaseRedisRepository_CountAll_Call) RunAndReturn(run func(context.Context) (int64, error)) *IBaseRedisRepository_CountAll_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: Ctx, prefix, key, value, expiration
func (_m *IBaseRedisRepository) Create(Ctx context.Context, prefix string, key string, value interface{}, expiration time.Duration) (string, error) {
	ret := _m.Called(Ctx, prefix, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}, time.Duration) (string, error)); ok {
		return rf(Ctx, prefix, key, value, expiration)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}, time.Duration) string); ok {
		r0 = rf(Ctx, prefix, key, value, expiration)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, interface{}, time.Duration) error); ok {
		r1 = rf(Ctx, prefix, key, value, expiration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBaseRedisRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type IBaseRedisRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - Ctx context.Context
//   - prefix string
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *IBaseRedisRepository_Expecter) Create(Ctx interface{}, prefix interface{}, key interface{}, value interface{}, expiration interface{}) *IBaseRedisRepository_Create_Call {
	return &IBaseRedisRepository_Create_Call{Call: _e.mock.On("Create", Ctx, prefix, key, value, expiration)}
}

func (_c *IBaseRedisRepository_Create_Call) Run(run func(Ctx context.Context, prefix string, key string, value interface{}, expiration time.Duration)) *IBaseRedisRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(interface{}), args[4].(time.Duration))
	})
	return _c
}

func (_c *IBaseRedisRepository_Create_Call) Return(_a0 string, _a1 error) *IBaseRedisRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IBaseRedisRepository_Create_Call) RunAndReturn(run func(context.Context, string, string, interface{}, time.Duration) (string, error)) *IBaseRedisRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: Ctx, prefix, key
func (_m *IBaseRedisRepository) Delete(Ctx context.Context, prefix string, key string) (int64, error) {
	ret := _m.Called(Ctx, prefix, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(Ctx, prefix, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(Ctx, prefix, key)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(Ctx, prefix, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBaseRedisRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type IBaseRedisRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - Ctx context.Context
//   - prefix string
//   - key string
func (_e *IBaseRedisRepository_Expecter) Delete(Ctx interface{}, prefix interface{}, key interface{}) *IBaseRedisRepository_Delete_Call {
	return &IBaseRedisRepository_Delete_Call{Call: _e.mock.On("Delete", Ctx, prefix, key)}
}

func (_c *IBaseRedisRepository_Delete_Call) Run(run func(Ctx context.Context, prefix string, key string)) *IBaseRedisRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IBaseRedisRepository_Delete_Call) Return(_a0 int64, _a1 error) *IBaseRedisRepository_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IBaseRedisRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) (int64, error)) *IBaseRedisRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKey provides a mock function with given fields: Ctx, prefix, key
func (_m *IBaseRedisRepository) GetByKey(Ctx context.Context, prefix string, key string) (string, error) {
	ret := _m.Called(Ctx, prefix, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(Ctx, prefix, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(Ctx, prefix, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(Ctx, prefix, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBaseRedisRepository_GetByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKey'
type IBaseRedisRepository_GetByKey_Call struct {
	*mock.Call
}

// GetByKey is a helper method to define mock.On call
//   - Ctx context.Context
//   - prefix string
//   - key string
func (_e *IBaseRedisRepository_Expecter) GetByKey(Ctx interface{}, prefix interface{}, key interface{}) *IBaseRedisRepository_GetByKey_Call {
	return &IBaseRedisRepository_GetByKey_Call{Call: _e.mock.On("GetByKey", Ctx, prefix, key)}
}

func (_c *IBaseRedisRepository_GetByKey_Call) Run(run func(Ctx context.Context, prefix string, key string)) *IBaseRedisRepository_GetByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IBaseRedisRepository_GetByKey_Call) Return(_a0 string, _a1 error) *IBaseRedisRepository_GetByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IBaseRedisRepository_GetByKey_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *IBaseRedisRepository_GetByKey_Call {
	_c.Call.Return(run)
	return _c
}

// IsExist provides a mock function with given fields: Ctx, prefix, key
func (_m *IBaseRedisRepository) IsExist(Ctx context.Context, prefix string, key string) (bool, error) {
	ret := _m.Called(Ctx, prefix, key)

	if len(ret) == 0 {
		panic("no return value specified for IsExist")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(Ctx, prefix, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(Ctx, prefix, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(Ctx, prefix, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBaseRedisRepository_IsExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExist'
type IBaseRedisRepository_IsExist_Call struct {
	*mock.Call
}

// IsExist is a helper method to define mock.On call
//   - Ctx context.Context
//   - prefix string
//   - key string
func (_e *IBaseRedisRepository_Expecter) IsExist(Ctx interface{}, prefix interface{}, key interface{}) *IBaseRedisRepository_IsExist_Call {
	return &IBaseRedisRepository_IsExist_Call{Call: _e.mock.On("IsExist", Ctx, prefix, key)}
}

func (_c *IBaseRedisRepository_IsExist_Call) Run(run func(Ctx context.Context, prefix string, key string)) *IBaseRedisRepository_IsExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IBaseRedisRepository_IsExist_Call) Return(_a0 bool, _a1 error) *IBaseRedisRepository_IsExist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IBaseRedisRepository_IsExist_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *IBaseRedisRepository_IsExist_Call {
	_c.Call.Return(run)
	return _c
}

// ManyToGet provides a mock function with given fields: Ctx, keys
func (_m *IBaseRedisRepository) ManyToGet(Ctx context.Context, keys []string) ([]interface{}, error) {
	ret := _m.Called(Ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for ManyToGet")
	}

	var r0 []interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]interface{}, error)); ok {
		return rf(Ctx, keys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []interface{}); ok {
		r0 = rf(Ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(Ctx, keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBaseRedisRepository_ManyToGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ManyToGet'
type IBaseRedisRepository_ManyToGet_Call struct {
	*mock.Call
}

// ManyToGet is a helper method to define mock.On call
//   - Ctx context.Context
//   - keys []string
func (_e *IBaseRedisRepository_Expecter) ManyToGet(Ctx interface{}, keys interface{}) *IBaseRedisRepository_ManyToGet_Call {
	return &IBaseRedisRepository_ManyToGet_Call{Call: _e.mock.On("ManyToGet", Ctx, keys)}
}

func (_c *IBaseRedisRepository_ManyToGet_Call) Run(run func(Ctx context.Context, keys []string)) *IBaseRedisRepository_ManyToGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *IBaseRedisRepository_ManyToGet_Call) Return(_a0 []interface{}, _a1 error) *IBaseRedisRepository_ManyToGet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IBaseRedisRepository_ManyToGet_Call) RunAndReturn(run func(context.Context, []string) ([]interface{}, error)) *IBaseRedisRepository_ManyToGet_Call {
	_c.Call.Return(run)
	return _c
}

// SetDTO provides a mock function with given fields: Ctx, prefix, obj
func (_m *IBaseRedisRepository) SetDTO(Ctx context.Context, prefix string, obj dto.SessionDTO) (string, error) {
	ret := _m.Called(Ctx, prefix, obj)

	if len(ret) == 0 {
		panic("no return value specified for SetDTO")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.SessionDTO) (string, error)); ok {
		return rf(Ctx, prefix, obj)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.SessionDTO) string); ok {
		r0 = rf(Ctx, prefix, obj)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.SessionDTO) error); ok {
		r1 = rf(Ctx, prefix, obj)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IBaseRedisRepository_SetDTO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDTO'
type IBaseRedisRepository_SetDTO_Call struct {
	*mock.Call
}

// SetDTO is a helper method to define mock.On call
//   - Ctx context.Context
//   - prefix string
//   - obj dto.SessionDTO
func (_e *IBaseRedisRepository_Expecter) SetDTO(Ctx interface{}, prefix interface{}, obj interface{}) *IBaseRedisRepository_SetDTO_Call {
	return &IBaseRedisRepository_SetDTO_Call{Call: _e.mock.On("SetDTO", Ctx, prefix, obj)}
}

func (_c *IBaseRedisRepository_SetDTO_Call) Run(run func(Ctx context.Context, prefix string, obj dto.SessionDTO)) *IBaseRedisRepository_SetDTO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(dto.SessionDTO))
	})
	return _c
}

func (_c *IBaseRedisRepository_SetDTO_Call) Return(_a0 string, _a1 error) *IBaseRedisRepository_SetDTO_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IBaseRedisRepository_SetDTO_Call) RunAndReturn(run func(context.Context, string, dto.SessionDTO) (string, error)) *IBaseRedisRepository_SetDTO_Call {
	_c.Call.Return(run)
	return _c
}

// NewIBaseRedisRepository creates a new instance of IBaseRedisRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBaseRedisRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IBaseRedisRepository {
	mock := &IBaseRedisRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
