// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "libs/src/internal/domain/models"

	mock "github.com/stretchr/testify/mock"
)

// IUserRepository is an autogenerated mock type for the IUserRepository type
type IUserRepository struct {
	mock.Mock
}

type IUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IUserRepository) EXPECT() *IUserRepository_Expecter {
	return &IUserRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: Ctx, filter, args
func (_m *IUserRepository) Count(Ctx context.Context, filter string, args ...interface{}) (int64, error) {
	var _ca []interface{}
	_ca = append(_ca, Ctx, filter)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (int64, error)); ok {
		return rf(Ctx, filter, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) int64); ok {
		r0 = rf(Ctx, filter, args...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(Ctx, filter, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUserRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type IUserRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - Ctx context.Context
//   - filter string
//   - args ...interface{}
func (_e *IUserRepository_Expecter) Count(Ctx interface{}, filter interface{}, args ...interface{}) *IUserRepository_Count_Call {
	return &IUserRepository_Count_Call{Call: _e.mock.On("Count",
		append([]interface{}{Ctx, filter}, args...)...)}
}

func (_c *IUserRepository_Count_Call) Run(run func(Ctx context.Context, filter string, args ...interface{})) *IUserRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *IUserRepository_Count_Call) Return(_a0 int64, _a1 error) *IUserRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUserRepository_Count_Call) RunAndReturn(run func(context.Context, string, ...interface{}) (int64, error)) *IUserRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: Ctx, obj
func (_m *IUserRepository) Create(Ctx context.Context, obj *domain.User) error {
	ret := _m.Called(Ctx, obj)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(Ctx, obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type IUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - Ctx context.Context
//   - obj *domain.User
func (_e *IUserRepository_Expecter) Create(Ctx interface{}, obj interface{}) *IUserRepository_Create_Call {
	return &IUserRepository_Create_Call{Call: _e.mock.On("Create", Ctx, obj)}
}

func (_c *IUserRepository_Create_Call) Run(run func(Ctx context.Context, obj *domain.User)) *IUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *IUserRepository_Create_Call) Return(_a0 error) *IUserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUserRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.User) error) *IUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteById provides a mock function with given fields: Ctx, id
func (_m *IUserRepository) DeleteById(Ctx context.Context, id int64) error {
	ret := _m.Called(Ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(Ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUserRepository_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type IUserRepository_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - Ctx context.Context
//   - id int64
func (_e *IUserRepository_Expecter) DeleteById(Ctx interface{}, id interface{}) *IUserRepository_DeleteById_Call {
	return &IUserRepository_DeleteById_Call{Call: _e.mock.On("DeleteById", Ctx, id)}
}

func (_c *IUserRepository_DeleteById_Call) Run(run func(Ctx context.Context, id int64)) *IUserRepository_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *IUserRepository_DeleteById_Call) Return(_a0 error) *IUserRepository_DeleteById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUserRepository_DeleteById_Call) RunAndReturn(run func(context.Context, int64) error) *IUserRepository_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteQuery provides a mock function with given fields: Ctx, query, args
func (_m *IUserRepository) ExecuteQuery(Ctx context.Context, query string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, Ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteQuery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) error); ok {
		r0 = rf(Ctx, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUserRepository_ExecuteQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteQuery'
type IUserRepository_ExecuteQuery_Call struct {
	*mock.Call
}

// ExecuteQuery is a helper method to define mock.On call
//   - Ctx context.Context
//   - query string
//   - args ...interface{}
func (_e *IUserRepository_Expecter) ExecuteQuery(Ctx interface{}, query interface{}, args ...interface{}) *IUserRepository_ExecuteQuery_Call {
	return &IUserRepository_ExecuteQuery_Call{Call: _e.mock.On("ExecuteQuery",
		append([]interface{}{Ctx, query}, args...)...)}
}

func (_c *IUserRepository_ExecuteQuery_Call) Run(run func(Ctx context.Context, query string, args ...interface{})) *IUserRepository_ExecuteQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *IUserRepository_ExecuteQuery_Call) Return(_a0 error) *IUserRepository_ExecuteQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUserRepository_ExecuteQuery_Call) RunAndReturn(run func(context.Context, string, ...interface{}) error) *IUserRepository_ExecuteQuery_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function with given fields: Ctx, query, args
func (_m *IUserRepository) Filter(Ctx context.Context, query string, args ...interface{}) ([]domain.User, error) {
	var _ca []interface{}
	_ca = append(_ca, Ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) ([]domain.User, error)); ok {
		return rf(Ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) []domain.User); ok {
		r0 = rf(Ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(Ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUserRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type IUserRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - Ctx context.Context
//   - query string
//   - args ...interface{}
func (_e *IUserRepository_Expecter) Filter(Ctx interface{}, query interface{}, args ...interface{}) *IUserRepository_Filter_Call {
	return &IUserRepository_Filter_Call{Call: _e.mock.On("Filter",
		append([]interface{}{Ctx, query}, args...)...)}
}

func (_c *IUserRepository_Filter_Call) Run(run func(Ctx context.Context, query string, args ...interface{})) *IUserRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *IUserRepository_Filter_Call) Return(_a0 []domain.User, _a1 error) *IUserRepository_Filter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUserRepository_Filter_Call) RunAndReturn(run func(context.Context, string, ...interface{}) ([]domain.User, error)) *IUserRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: Ctx
func (_m *IUserRepository) GetAll(Ctx context.Context) ([]domain.User, error) {
	ret := _m.Called(Ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.User, error)); ok {
		return rf(Ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.User); ok {
		r0 = rf(Ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(Ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUserRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type IUserRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - Ctx context.Context
func (_e *IUserRepository_Expecter) GetAll(Ctx interface{}) *IUserRepository_GetAll_Call {
	return &IUserRepository_GetAll_Call{Call: _e.mock.On("GetAll", Ctx)}
}

func (_c *IUserRepository_GetAll_Call) Run(run func(Ctx context.Context)) *IUserRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IUserRepository_GetAll_Call) Return(_a0 []domain.User, _a1 error) *IUserRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUserRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]domain.User, error)) *IUserRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: Ctx, id
func (_m *IUserRepository) GetById(Ctx context.Context, id int64) (domain.User, error) {
	ret := _m.Called(Ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.User, error)); ok {
		return rf(Ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.User); ok {
		r0 = rf(Ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(Ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUserRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type IUserRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - Ctx context.Context
//   - id int64
func (_e *IUserRepository_Expecter) GetById(Ctx interface{}, id interface{}) *IUserRepository_GetById_Call {
	return &IUserRepository_GetById_Call{Call: _e.mock.On("GetById", Ctx, id)}
}

func (_c *IUserRepository_GetById_Call) Run(run func(Ctx context.Context, id int64)) *IUserRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *IUserRepository_GetById_Call) Return(_a0 domain.User, _a1 error) *IUserRepository_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUserRepository_GetById_Call) RunAndReturn(run func(context.Context, int64) (domain.User, error)) *IUserRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function with given fields: Ctx, username
func (_m *IUserRepository) GetByUsername(Ctx context.Context, username string) (domain.User, error) {
	ret := _m.Called(Ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(Ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(Ctx, username)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(Ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUserRepository_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type IUserRepository_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - Ctx context.Context
//   - username string
func (_e *IUserRepository_Expecter) GetByUsername(Ctx interface{}, username interface{}) *IUserRepository_GetByUsername_Call {
	return &IUserRepository_GetByUsername_Call{Call: _e.mock.On("GetByUsername", Ctx, username)}
}

func (_c *IUserRepository_GetByUsername_Call) Run(run func(Ctx context.Context, username string)) *IUserRepository_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IUserRepository_GetByUsername_Call) Return(_a0 domain.User, _a1 error) *IUserRepository_GetByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUserRepository_GetByUsername_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *IUserRepository_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateById provides a mock function with given fields: Ctx, id, updateFields
func (_m *IUserRepository) UpdateById(Ctx context.Context, id int64, updateFields map[string]interface{}) error {
	ret := _m.Called(Ctx, id, updateFields)

	if len(ret) == 0 {
		panic("no return value specified for UpdateById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, map[string]interface{}) error); ok {
		r0 = rf(Ctx, id, updateFields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUserRepository_UpdateById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateById'
type IUserRepository_UpdateById_Call struct {
	*mock.Call
}

// UpdateById is a helper method to define mock.On call
//   - Ctx context.Context
//   - id int64
//   - updateFields map[string]interface{}
func (_e *IUserRepository_Expecter) UpdateById(Ctx interface{}, id interface{}, updateFields interface{}) *IUserRepository_UpdateById_Call {
	return &IUserRepository_UpdateById_Call{Call: _e.mock.On("UpdateById", Ctx, id, updateFields)}
}

func (_c *IUserRepository_UpdateById_Call) Run(run func(Ctx context.Context, id int64, updateFields map[string]interface{})) *IUserRepository_UpdateById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *IUserRepository_UpdateById_Call) Return(_a0 error) *IUserRepository_UpdateById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUserRepository_UpdateById_Call) RunAndReturn(run func(context.Context, int64, map[string]interface{}) error) *IUserRepository_UpdateById_Call {
	_c.Call.Return(run)
	return _c
}

// NewIUserRepository creates a new instance of IUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserRepository {
	mock := &IUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
