github: https://github.com/snickyyy/Online-Chat-Golang

app:
  secret_key: "${APP_SECRET_KEY}"
  name: "GoChat"
  mode: "dev"
  port: 8000
  debug: true
  domain_name: "127.0.0.1"

db:
  host: "${DB_HOST}"
  port: 5432
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  database: "postgres"
  sslmode: "${DB_SSL_MODE}"

auth:
  session_auth_ttl: 86400
  confirm_email_ttl: 3600

mongo:
  uri: "${MONGO_URI}"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db:
    session: 0
    message: 1

mail:
  username: "${MAIL_USERNAME}"
  password: "${MAIL_PASSWORD}"
  from:     "${MAIL_FROM}"
  port:     "${MAIL_PORT}"
  server:   "${MAIL_SERVER}"
