github: https://github.com/snickyyy/Online-Chat-Golang

app:
  secret_key: "${APP_SECRET_KEY}"
  name: "GoChat"
  mode: "dev"
  port: 8000
  debug: true
  domain_name: "127.0.0.1"

db:
  host: "${DB_HOST}"
  port: 5432
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  database: "postgres"
  sslmode: "${DB_SSL_MODE}"

auth:
  session_auth_ttl: 86400
  confirm_email_ttl: 3600
  reset_password_ttl: 600
  time_to_change_password: 86400

mongo:
  uri: "${MONGO_URI}"

redis:
  host: "redis"
  port: 6379
  password: ""
  prefixes:
    session: "session:"
    message: "message:"
    confirm_email: "confirm_email:"
    confirm_reset_password: "confirm_reset_password:"

pagination:
  chat_list: 25
  global_chat_list: 20
  messages_list: 100
  users_in_chat: 20
  search_users_list: 20

mail:
  username: "${MAIL_USERNAME}"
  password: "${MAIL_PASSWORD}"
  from:     "${MAIL_FROM}"
  port:     "${MAIL_PORT}"
  server:   "${MAIL_SERVER}"
