// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"libs/src/settings"
)

// Injectors from wire.go:

func InitializeApp() (*settings.App, error) {
	baseConfig, err := settings.GetBaseConfig()
	if err != nil {
		return nil, err
	}
	db, err := settings.InitDb(baseConfig)
	if err != nil {
		return nil, err
	}
	logger, err := settings.InitLogger(baseConfig)
	if err != nil {
		return nil, err
	}
	app := settings.NewApp(db, logger, baseConfig)
	return app, nil
}
