name: CI for OCG

on:
    push:
        branches:
        - main
    pull_request:
        branches:
          - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.5'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.52.2/golangci-lint-1.52.2-linux-amd64.tar.gz | tar -xz -C /usr/local/bin

      - name: Run linters
        run: golangci-lint run ./...

  build:
    runs-on: ubuntu-latest
    env:
      APP_MODE: "dev"
      APP_PORT: "8000"
      APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
        continue-on-error: false

      - name: Check Docker Compose version
        run: docker-compose --version

      - name: Run build
        run: make start

      - name: Wait a bit
        run: sleep 10

      - name: Shutdown
        run: make stop

  test:
    runs-on: ubuntu-latest
    env:
      APP_MODE: "dev"
      APP_PORT: "8000"
      APP_SECRET_KEY: testtesttesttesttesttesttesttest
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: testDB
      MONGO_URI: mongodb://mongo:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
        continue-on-error: false

      - name: Check Docker Compose version
        run: docker-compose --version

      - name: Run integration tests
        run: make test-integration

      - name: Run unit tests
        run: make test-unit
